# Количество островов на карте
IslandCount = 8
# Включить логи в консоль
Logs = true

[ship]
# Масса в кг
mass = 50000.0

# Размеры корпуса
length = 10.0
beam = 3.0
draft = 1.2
height = 3.0

# Стартовые параметры корабля
startSpeed = 0.0
startAngle = 270.0
[ship.startPosition]
X = 900
Y = 500

[wind]
# Влияние ветра
X = 0.2
Y = 0.2

[flow]
# Течение воды
X = 0.2
Y = 0.2
