# Количество островов на карте
IslandCount = 12
# Включить логи в консоль
Logs = false

[ship]
# Масса в кг
mass = 50000.0

# Размеры корпуса
length = 10.0
beam = 3.0
draft = 1.2
height = 3.0

# Стартовая позиция
[ship.startPosition]
X = 9.0
Y = 5.0

# Стартовые параметры движения
startAngle = 0.0   # В радианах
startSpeed = 0.0   # Начальная скорость

[wind]
# Влияние ветра
X = 0.0
Y = 0.0

[flow]
# Течение воды
X = 1.0
Y = 1.0
