# Конфигурация корабля
[ship]
mass = 50000          # Масса корабля
length = 10           # Длина
beam = 3              # Ширина
draft = 1             # Осадка
height = 3            # Высота
startAngle = 0.0      # Начальный угол
startSpeed = 0        # Начальная скорость

# Начальная позиция корабля на карте
[ship.startPosition]
X = 0.0
Y = 0.0
